# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-06-16 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nomPrenom', models.CharField(default='fullName', max_length=200)),
                ('nom', models.CharField(default='nom', max_length=100)),
                ('prenom', models.CharField(default='prenom', max_length=100)),
                ('date_ajout', models.DateTimeField()),
                ('num_mobile', models.CharField(default='phoneNumber', max_length=100)),
                ('num_personelle', models.CharField(default='phoneNumber', max_length=100)),
                ('num_prof', models.CharField(default='phoneNumber', max_length=100)),
                ('email', models.EmailField(default='email', max_length=100)),
            ],
            options={
                'db_table': 'raspberry_app_contact',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('date_envoie', models.DateTimeField()),
                ('msg_body', models.CharField(default='default_msg', max_length=160)),
            ],
            options={
                'db_table': 'raspberry_app_message',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(default='defaultUsername', max_length=100)),
                ('usernameCanonical', models.CharField(default='defaultusernameCanonical', max_length=100)),
                ('password', models.CharField(default='defaultpassword', max_length=100)),
                ('email', models.EmailField(default='defaultEmail', max_length=100)),
                ('emailCanonical', models.EmailField(default='defaultEmail', max_length=100)),
                ('date_inscription', models.DateTimeField(default=datetime.datetime(2016, 6, 16, 21, 28, 13, 287170), verbose_name="Date d'inscription")),
                ('derniere_connexion', models.DateTimeField(default=datetime.datetime(2016, 6, 16, 21, 28, 13, 287170), verbose_name='Date de derniere connexion')),
                ('confirmationToken', models.CharField(default='defaultConfirmationToken', max_length=100)),
                ('enabled', models.BooleanField(default='True')),
                ('locked', models.BooleanField(default='False')),
                ('roles', models.CharField(choices=[('SU', 'ADMIN'), ('US', 'SIMPLE_USER')], default='SIMPLE_USER', max_length=2)),
            ],
            options={
                'db_table': 'raspberry_app_utilisateur',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='utilisateur',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='raspberry_app.Utilisateur'),
        ),
    ]
