# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-06-26 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raspberry_app', '0002_auto_20160626_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conv_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raspberry_app.Contact')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'raspberry_app_conversation',
            },
        ),
    ]
